#!/bin/sh

VERSION="5.3"
rm -f usr/local/bin/snapraid

if [ ! -d "snapraid-${VERSION}" ]; then
  wget http://sourceforge.net/projects/snapraid/files/snapraid-${VERSION}.tar.gz/download -O snapraid-${VERSION}.tar.gz
  tar xzf snapraid-${VERSION}.tar.gz
  /bin/rm -f snapraid-${VERSION}.tar.gz
fi

cd snapraid-${VERSION}
./configure
make clean
make
cp snapraid ../usr/local/bin/
