#!/bin/sh

# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Stephane Bocquet <stephane_bocquet@hotmail.com>
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2011 Stephane Bocquet
# @copyright Copyright (c) 2011-2012 Marcel Beck
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


OMV_SAMBA_CONFIG=${OMV_SAMBA_CONFIG:-"/etc/samba/smb.conf"}

if [ "$(omv_config_get "//services/snapraid/pool")" != "1" ]; then
    exit 0
fi

POOL_DIR="/media/pool"
pool_name=$(omv_config_get "//services/snapraid/pool_name")

cat <<EOF >> ${OMV_SAMBA_CONFIG}

#======== Snapraid Pool ========
[${pool_name}]
comment = ${pool_name}
path = ${POOL_DIR}
read only = yes
guest ok = yes
wide links = yes
EOF