#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="snapraid"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "blocksize" "256"
            omv_config_add_element "${SERVICE_XPATH}" "autosave" "0"
            omv_config_add_element "${SERVICE_XPATH}" "nohidden" "0"
            omv_config_add_element "${SERVICE_XPATH}" "pool" "0"
            omv_config_add_element "${SERVICE_XPATH}" "poolname" ""
            omv_config_add_element "${SERVICE_XPATH}" "syslog" "1"
            omv_config_add_element "${SERVICE_XPATH}" "debug" "0"
            omv_config_add_element "${SERVICE_XPATH}" "sendmail" "1"
            omv_config_add_element "${SERVICE_XPATH}" "runscrub" "1"
            omv_config_add_element "${SERVICE_XPATH}" "scrubfreq" "7"
            omv_config_add_element "${SERVICE_XPATH}" "delthreshold" "0"
            omv_config_add_element "${SERVICE_XPATH}" "percentscrub" "12"
            omv_config_add_element "${SERVICE_XPATH}" "scrubpercent" "100"
            omv_config_add_element "${SERVICE_XPATH}" "drives" ""
            omv_config_add_element "${SERVICE_XPATH}" "rules" ""
        fi

        omv-mkconf snapraid

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
